name: Deploy to Netlify

on:
  push:
    branches:
      - main
    paths:
      - 'Frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Frontend to Netlify
        run: |
          npm install -g netlify-cli
          netlify deploy --dir Frontend --site daaadd6f-857a-4e65-838f-1c43a2962dc6 --prod --auth nfp_5qTQ5cTWWEFAdG1RYcPjQ6SbxooVYRCnce96